### ISSUE TITLE
this is joke

### ISSUE THREAD

**Issue by xseano** [InfinityStudios/OpenOTP#5]
this isnt work and not realtime u guys suck omg stop code mans

**Comment by PythonPsychonaut** [comment]
I have a custom version of Astron in the works, and I use RealTime, why wont they change to it? No idea.

**Comment by itsinfinity** [comment]
This is realtime?

**Comment by itsinfinity** [comment]
If this was one of the other OTP remakes, (ex py-otp) i would have a DatabaseServer etc.

**Comment by toonjoey** [comment]
This is definitely a joke issue...let's keep it though. I kinda chuckled.
